### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by abmami** [abmami/Keywords-Extraction-from-French-Documents#2]
- [x] Update fine-tuning notebook for KE task
- [x] Add KE task to the pipeline script
- [x] Add inference for both tasks
