### ISSUE TITLE
TODO 3

### ISSUE THREAD

**Issue by abmami** [abmami/Keywords-Extraction-from-French-Documents#6]
- [x] Test for inference and app
- [x] Push quantized models and app
- [x] Update requirements.txt
- [x] Update README.md
